### ISSUE TITLE
Fails on repository with "." in it

### ISSUE THREAD

**Issue by kishorbhat** [wong2/first-commit#2]
I tried checking the first commit of my [blog](https://github.com/kbhat95/kbhat95.github.io), and it fails.

Looking at the url, the repository name is getting truncated to just `kbhat95`, i.e., the url becomes `http://first-commit.com/kbhat95/kbhat95`.

**Comment by wong2** [comment]
fixed: http://first-commit.com/kbhat95/kbhat95.github.io  thanks for your report
