### ISSUE TITLE
Wrong link to commit

### ISSUE THREAD

**Issue by crazy4groovy** [wong2/first-commit#7]
input:
`https://github.com/attic-labs/noms`

gave me:
`https://github.com/tenant:1:repo:36778364`

but should be:
`https://github.com/attic-labs/noms/commit/68c3ac02058e559367534aeeb7d9f8f483a4db1b` (currently on page 78)

**Comment by wong2** [comment]
Github changed their HTML structure, I've updated first-commit, thanks

**Comment by crazy4groovy** [comment]
:+1:  That's the issue with screen scrapers :wink:
