### ISSUE TITLE
Better way of finding the first commit 

### ISSUE THREAD

**Issue by JamesWP** [wong2/first-commit#9]
Here is another solution to finding the first commit I came up with, thought this project could be improved with it

https://gist.github.com/JamesWP/bc3622dd3d94bf6cbeb5c83b7f183b55

**Comment by wong2** [comment]
@JamesWP great! I'll give it a try

**Comment by wong2** [comment]
@JamesWP thanks for your method, but it can't be used on the server side due to github api's rate limit

**Comment by wong2** [comment]
@JamesWP thanks for your method, but it can't be used on the server side due to github api's rate limit
